/**
 * Created by luis on 5/23/2016.
 */
export default {

    SET_SORTER:"SET_SORTER",
    SET_CURRENCY:"SET_CURRENCY",
    SET_DATE_CURRENCY:"SET_DATE_CURRENCY",
    //LOGIN REQUEST
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    //SIGNUP REQUEST
    SIGNUP_REQUEST:"SIGNUP_REQUEST",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAILURE:"SIGNUP_FAILURE",
    //TRANSACTION REQUEST
    TRANSACTION_REQUEST:"TRANSACTION_REQUEST",
    TRANSACTION_SUCCESS:"TRANSACTION_SUCCESS",
    TRANSACTION_FAILURE:"TRANSACTION_FAILURE",
    //TRANSACTION REQUEST
    CURRENCY_REQUEST:"CURRENCY_REQUEST",
    CURRENCY_SUCCESS:"CURRENCY_SUCCESS",
    CURRENCY_FAILURE:"CURRENCY_FAILURE",
    //ADD REQUEST
    ADD_REQUEST:"ADD_REQUEST",
    ADD_SUCCESS:"ADD_SUCCESS",
    ADD_FAILURE:"ADD_FAILURE",
    //EDIT REQUEST
    EDIT_REQUEST:"EDIT_REQUEST",
    EDIT_SUCCESS:"EDIT_SUCCESS",
    EDIT_FAILURE:"EDIT_FAILURE",
    //LOGOUT
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    //RESET
    RESET_APP:"RESET_APP"
}